from ollama/ollama

run apt-get update && apt-get install -y wget && rm -rf /var/lib/apt/lists/*

copy ./Modelfile /Modelfile
copy ./entrypoint.ollama.sh /entrypoint.ollama.sh

run chmod +x /entrypoint.ollama.sh

entrypoint ["/entrypoint.ollama.sh"]