services:
  backend:
    build:
      context: ./Backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - ml-api
      - postgres
    networks:
      - app-network

  ml-api:
    build:
      context: ./ML
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - ollama
    networks:
      - app-network

  ollama:
    build:
      context: ./ML
      dockerfile: Dockerfile.ollama
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - "11434:11434"
    # если есть gpu - раскомментировать
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    networks:
      - app-network

  postgres:
    image: postgres:17
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  ollama-data:
  postgres-data:
